/*
 * Copyright (c) 2007-2011 Artigile.
 * Software development company.
 * All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Artigile. ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with Artigile software company.
 */

package com.artigile.warehouse.gui.menuitems.details.catalog;

import com.artigile.warehouse.gui.core.properties.PropertiesForm;
import com.artigile.warehouse.gui.core.properties.data.validation.DataValidationException;
import com.artigile.warehouse.gui.core.report.controller.TreeReport;
import com.artigile.warehouse.gui.core.report.controller.TreeReportViewType;
import com.artigile.warehouse.gui.utils.GridLayoutUtils;
import com.artigile.warehouse.utils.dto.details.DetailCatalogStructureTO;
import com.artigile.warehouse.utils.i18n.I18nSupport;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * @author Shyrik, 03.01.2009
 */
public class DetailCatalogStructureForm implements PropertiesForm {
    private JPanel groupsPanel;

    boolean canEdit;
    DetailCatalogStructureTO catalogStructure;
    DetailCatalogStructureTO tempCatalogStructure; //Copy of the structure for safe editing groups.

    public DetailCatalogStructureForm(DetailCatalogStructureTO catalogStructure, boolean canEdit) {
        this.canEdit = canEdit;
        this.catalogStructure = catalogStructure;

        this.tempCatalogStructure = new DetailCatalogStructureTO();
        this.tempCatalogStructure.copyFrom(catalogStructure);
    }

    @Override
    public String getTitle() {
        return I18nSupport.message("detail.catalog.structure.properties.title");
    }

    @Override
    public JPanel getContentPanel() {
        return groupsPanel;
    }

    @Override
    public boolean canSaveData() {
        return canEdit;
    }

    @Override
    public void loadData() {
        TreeReport detailGroupsTree = new TreeReport(new DetailCatalogTree(tempCatalogStructure), TreeReportViewType.TREE_TABLE);
        groupsPanel.add(detailGroupsTree.getReportComponent(), GridLayoutUtils.getGrowingAndFillingCellConstraints());
    }

    @Override
    public void validateData() throws DataValidationException {
    }

    @Override
    public void saveData() {
        catalogStructure.setRootGroups(tempCatalogStructure.getRootGroups());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        groupsPanel = new JPanel();
        groupsPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        groupsPanel.setMinimumSize(new Dimension(500, 400));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return groupsPanel;
    }
}
