/*
 * Copyright (c) 2007-2011 Artigile.
 * Software art development company.
 * All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Artigile. ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with Artigile software company.
 */

package com.artigile.warehouse.gui.menuitems.complecting.printing;

import com.artigile.warehouse.gui.core.properties.PropertiesForm;
import com.artigile.warehouse.gui.core.properties.data.validation.DataValidation;
import com.artigile.warehouse.gui.core.properties.data.validation.DataValidationException;
import com.artigile.warehouse.utils.i18n.I18nSupport;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.util.ResourceBundle;

/**
 * @author Shyrik, 16.05.2009
 */
public class ComplectingTasksPrintPropertiesForm implements PropertiesForm {
    private JPanel contentPanel;
    private JCheckBox fieldPositions;
    private JCheckBox fieldStickers;
    private JRadioButton fieldPrintAll;
    private JRadioButton fieldPrintNotPrinted;
    private JRadioButton fieldPrintProblem;
    private JRadioButton fieldPrintSelected;


    private ComplectingTasksPrintOptions printOptions;

    public ComplectingTasksPrintPropertiesForm(ComplectingTasksPrintOptions printOptions) {
        this.printOptions = printOptions;
    }

    @Override
    public String getTitle() {
        return I18nSupport.message("complectingTask.printForm.title");
    }

    @Override
    public JPanel getContentPanel() {
        return contentPanel;
    }

    @Override
    public boolean canSaveData() {
        return true;
    }

    @Override
    public void loadData() {
        fieldPositions.setSelected(printOptions.isPrintPositions());
        fieldStickers.setSelected(printOptions.isPrintStickers());
        fieldPrintAll.setSelected(printOptions.getWhatToPrint().equals(ComplectingTasksToPrintFilterType.ALL));
        fieldPrintNotPrinted.setSelected(printOptions.getWhatToPrint().equals(ComplectingTasksToPrintFilterType.NOT_PRINTED));
        fieldPrintProblem.setSelected(printOptions.getWhatToPrint().equals(ComplectingTasksToPrintFilterType.PROBLEM));
        fieldPrintSelected.setSelected(printOptions.getWhatToPrint().equals(ComplectingTasksToPrintFilterType.SELECTED));
    }

    @Override
    public void validateData() throws DataValidationException {
        DataValidation.checkCondition(fieldPositions.isSelected() || fieldStickers.isSelected(), null, "complectingTask.printForm.message.choosePrintingDocument");
    }

    @Override
    public void saveData() {
        printOptions.setPrintPositions(fieldPositions.isSelected());
        printOptions.setPrintStickers(fieldStickers.isSelected());
        if (fieldPrintAll.isSelected()) {
            printOptions.setWhatToPrint(ComplectingTasksToPrintFilterType.ALL);
        } else if (fieldPrintNotPrinted.isSelected()) {
            printOptions.setWhatToPrint(ComplectingTasksToPrintFilterType.NOT_PRINTED);
        } else if (fieldPrintProblem.isSelected()) {
            printOptions.setWhatToPrint(ComplectingTasksToPrintFilterType.PROBLEM);
        } else if (fieldPrintSelected.isSelected()) {
            printOptions.setWhatToPrint(ComplectingTasksToPrintFilterType.SELECTED);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        contentPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        fieldPositions = new JCheckBox();
        this.$$$loadButtonText$$$(fieldPositions, ResourceBundle.getBundle("i18n/warehouse").getString("complectingTask.printForm.positions"));
        panel1.add(fieldPositions, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldStickers = new JCheckBox();
        this.$$$loadButtonText$$$(fieldStickers, ResourceBundle.getBundle("i18n/warehouse").getString("complectingTask.printForm.stickers"));
        panel1.add(fieldStickers, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPanel.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        fieldPrintAll = new JRadioButton();
        this.$$$loadButtonText$$$(fieldPrintAll, ResourceBundle.getBundle("i18n/warehouse").getString("complectingTask.printForm.all"));
        panel2.add(fieldPrintAll, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldPrintNotPrinted = new JRadioButton();
        this.$$$loadButtonText$$$(fieldPrintNotPrinted, ResourceBundle.getBundle("i18n/warehouse").getString("complectingTask.printForm.notPrinted"));
        panel2.add(fieldPrintNotPrinted, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldPrintProblem = new JRadioButton();
        this.$$$loadButtonText$$$(fieldPrintProblem, ResourceBundle.getBundle("i18n/warehouse").getString("complectingTask.printForm.problem"));
        panel2.add(fieldPrintProblem, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldPrintSelected = new JRadioButton();
        this.$$$loadButtonText$$$(fieldPrintSelected, ResourceBundle.getBundle("i18n/warehouse").getString("complectingTask.printForm.selected"));
        panel2.add(fieldPrintSelected, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(fieldPrintAll);
        buttonGroup.add(fieldPrintNotPrinted);
        buttonGroup.add(fieldPrintProblem);
        buttonGroup.add(fieldPrintSelected);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadButtonText$$$(AbstractButton component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}

