/*
 * Copyright (c) 2007-2013 Artigile.
 * Software development company.
 * All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Artigile. ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with Artigile software company.
 */

package com.artigile.warehouse.gui.menuitems.settings;

import com.artigile.warehouse.bl.warehouseBatch.WarehouseBatchService;
import com.artigile.warehouse.domain.admin.PermissionType;
import com.artigile.warehouse.gui.core.plugin.FramePlugin;
import com.artigile.warehouse.gui.core.properties.data.validation.DataValidationException;
import com.artigile.warehouse.gui.core.report.command.availability.PermissionCommandAvailability;
import com.artigile.warehouse.gui.utils.UIComponentUtils;
import com.artigile.warehouse.utils.SpringServiceContext;
import com.artigile.warehouse.utils.i18n.I18nSupport;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;

/**
 * @author Aliaksandr.Chyrtsik, 05.01.13
 */
public class InventoryControlSettings extends FramePlugin {

    private JPanel contentPane;

    private JButton applySettings;

    private JCheckBox fieldWarehouseBatchTrackReceiptDateAndPrice;

    private JCheckBox fieldWarehouseBatchTrackShelfLifeDate;

    private WarehouseBatchService warehouseBatchService = SpringServiceContext.getInstance().getWarehouseBatchService();

    public InventoryControlSettings() {
        $$$setupUI$$$();
        initListeners();
        loadSettings();
    }

    private void initListeners() {
        boolean canSaveSettings = new PermissionCommandAvailability(PermissionType.EDIT_INVENTORY_CONTROL_SETTINGS).isAvailable(null);
        applySettings.setEnabled(canSaveSettings);
        if (canSaveSettings) {
            applySettings.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent event) {
                    // Check input data
                    try {
                        validateSettings();
                    } catch (DataValidationException e) {
                        UIComponentUtils.showCommentOnComponent(e.getComponent(), e.getMessage());
                        return;
                    }

                    //Save settings as validation passed.
                    saveSettings();
                }
            });
        }
    }

    private void loadSettings() {
        fieldWarehouseBatchTrackReceiptDateAndPrice.setSelected(warehouseBatchService.isTrackPostingItem());
        fieldWarehouseBatchTrackShelfLifeDate.setSelected(warehouseBatchService.isTrackShelfLife());
    }

    private void validateSettings() throws DataValidationException {
        //No validation is needed for now. Add validation rules as number of parameters will grow.
    }

    private void saveSettings() {
        warehouseBatchService.setTrackPostingItem(fieldWarehouseBatchTrackReceiptDateAndPrice.isSelected());
        warehouseBatchService.setTrackShelfLife(fieldWarehouseBatchTrackShelfLifeDate.isSelected());
    }

    @Override
    public String getTitle() {
        return I18nSupport.message("inventory.control.settings.title");
    }

    @Override
    public JPanel getContentPanel() {
        return contentPane;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(5, 5, 5, 5), -1, -1));
        contentPane.setBorder(BorderFactory.createTitledBorder(""));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 2, new Insets(1, 1, 4, 1), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), ResourceBundle.getBundle("i18n/warehouse").getString("inventory.control.settings.warehouse.batch.settings"), TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        fieldWarehouseBatchTrackReceiptDateAndPrice = new JCheckBox();
        this.$$$loadButtonText$$$(fieldWarehouseBatchTrackReceiptDateAndPrice, ResourceBundle.getBundle("i18n/warehouse").getString("inventory.control.settings.warehouse.batch.track.receipt.date.and.price"));
        panel1.add(fieldWarehouseBatchTrackReceiptDateAndPrice, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldWarehouseBatchTrackShelfLifeDate = new JCheckBox();
        this.$$$loadButtonText$$$(fieldWarehouseBatchTrackShelfLifeDate, ResourceBundle.getBundle("i18n/warehouse").getString("inventory.control.settings.warehouse.batch.track.shelf.life.date"));
        panel1.add(fieldWarehouseBatchTrackShelfLifeDate, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        applySettings = new JButton();
        applySettings.setEnabled(false);
        this.$$$loadButtonText$$$(applySettings, ResourceBundle.getBundle("i18n/warehouse").getString("common.apply.button"));
        panel2.add(applySettings, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        contentPane.add(spacer3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadButtonText$$$(AbstractButton component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
