/*
 * Copyright (c) 2007-2011 Artigile.
 * Software development company.
 * All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Artigile. ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with Artigile software company.
 */

package com.artigile.warehouse.gui.menuitems.postings.items;

import com.artigile.warehouse.bl.postings.PostingItemImportError;
import com.artigile.warehouse.gui.core.properties.ReadOnlyPropertiesForm;
import com.artigile.warehouse.gui.core.report.controller.TableReport;
import com.artigile.warehouse.gui.utils.GridLayoutUtils;
import com.artigile.warehouse.utils.i18n.I18nSupport;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * @author Aliaksandr.Chyrtsik, 07.11.11
 */
public class ImportPostingItemsResultForm implements ReadOnlyPropertiesForm {
    private JPanel contentPanel;

    private List<PostingItemImportError> errorItems;

    public ImportPostingItemsResultForm(List<PostingItemImportError> errorItems) {
        this.errorItems = errorItems;
    }

    @Override
    public String getTitle() {
        return I18nSupport.message("posting.items.import.result.properties.title");
    }

    @Override
    public JPanel getContentPanel() {
        return contentPanel;
    }

    @Override
    public void loadData() {
        TableReport resultsReport = new TableReport(new ImportPostingItemsResultsList(errorItems));
        JPanel resultsReportPanel = resultsReport.getContentPanel();
        resultsReportPanel.setMinimumSize(new Dimension(400, 300));
        contentPanel.add(resultsReportPanel, GridLayoutUtils.getGrowingAndFillingCellConstraints());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
